Repository HTL3R-Typst/htl3r-da, pull requests merged in 2024-12, with the labels that each got.

#10 Add bubbles
  src/lib.typ
  src/lib/assets/warning.svg
  src/lib/bubble.typ
  src/lib/settings.typ
Labels: enhancement

#12 8 add manual mode for the cheat sheet
  docs/manual.typ
  src/lib.typ
Labels: enhancement

#13 1 set author on subchapters
  src/lib/pages/abbreviation.typ
  src/lib/util.typ
Labels: enhancement

#14 11 add input validation
  src/lib.typ
  src/lib/validate.typ
  src/lib/validate.yml
Labels: documentation, enhancement

#15 9 add strict font checking
  src/lib.typ
  src/lib/font.typ
  src/lib/settings.typ
Labels: enhancement

#22 Delete deprecated example chapter
  docs/chapter/example.typ
Labels: documentation

#23 17 first time use of an abbreviation should footnote
  src/lib.typ
  src/lib/abbr.typ
  src/lib/settings.typ
Labels: enhancement

#26 remove checklist from README
  README.md
Labels: documentation

#27 25 conform to kebab case
  README.md
  docs/assets/code-example.sh
  docs/manual.typ
  src/lib.typ
  src/lib/abbr.typ
  src/lib/assets/htl3r-logo.svg
  src/lib/bubble.typ
  src/lib/font.typ
  src/lib/pages.typ
  src/lib/pages/abbreviation.typ
  src/lib/pages/abstract.typ
  src/lib/pages/bibliography.typ
  src/lib/pages/cover.typ
  src/lib/pages/glossary.typ
  src/lib/pages/preamble.typ
  src/lib/pages/printref.typ
  src/lib/pages/sworn-statement.typ
  src/lib/pages/toc.typ
  src/lib/pages/tof.typ
  src/lib/pages/tol.typ
  src/lib/pages/tot.typ
  src/lib/util.typ
  src/lib/validate.typ
  src/lib/validate.yml
  tests/doc/assets/code-example.sh
  tests/doc/chapter/example.typ
  tests/doc/test.typ
Labels: documentation

#30 Add missing template
  .gitignore
  template/abbr.yml
  template/chapter/example.typ
  template/main.typ
  template/refs.yml
  template/text/abstract.typ
  template/text/kurzfassung.typ
Labels: bug

#31 bring back 'DA_BEGIN' label
  src/lib.typ
Labels: bug

#37 36 allow windows/powershell usage of justfile
  Justfile
  README.md
  scripts/ps/package.ps1
  scripts/ps/setup.ps1
  scripts/ps/uninstall.ps1
Labels: enhancement

#39 Update README again (basically a rollback)
  README.md
Labels: documentation

#43 keep track of footnotes
  src/lib/abbr.typ
Labels: bug

#45 simple breadcrumbs implementation
  docs/manual.typ
  src/lib.typ
  src/lib/breadcrumbs.typ
  src/lib/settings.typ
Labels: enhancement
