Repository HTL3R-Typst/htl3r-da, pull requests merged in 2025-02, with the labels that each got.

#74 Add converted splunk syntax file
  src/lib.typ
  src/lib/assets/splunk.sublime-syntax
Labels: Mandatory v1.0

#77 62 official requirement change font and font size to match official templates
  docs/manual.pdf
  docs/manual.typ
  src/lib.typ
  src/lib/font.typ
  src/lib/settings.typ
  tests/doc/chapter/example.typ
Labels: bug, documentation, Mandatory v1.0

#79 adjust signature spacing
  src/lib/pages/sworn-statement.typ
Labels: bug, Mandatory v1.0

#84 Final cleanup of the manual
  docs/manual.typ
Labels: Mandatory v1.0

#86 yeah it's that easy
  src/lib/pages/abbreviation.typ
Labels: bug, Mandatory v1.0

#91 fix typst 0 13 0 compatibility
  docs/manual.pdf
  src/lib.typ
  src/lib/bubble.typ
  src/lib/pages/bibliography.typ
  src/lib/pages/glossary.typ
  src/lib/pages/toc.typ
  src/lib/pages/tof.typ
  src/lib/pages/tol.typ
  src/lib/pages/tot.typ
  src/lib/util.typ
  src/lib/validate.typ
Labels: bug
