Repository HTL3R-Typst/htl3r-da, pull requests merged in 2025-01, with the labels that each got.

#40 feat: add option for skipping blank pages
  docs/manual.typ
  src/lib.typ
  src/lib/global.typ
  src/lib/util.typ
  src/lib/validate.yml
Labels: enhancement

#49 basic implementation of inline todos
  docs/manual.typ
  src/lib.typ
  src/lib/bubble.typ
Labels: enhancement

#47 feat: first version of citation
  README.md
  src/lib.typ
  src/lib/assets/htl3r-citestyle/LICENSE
  src/lib/assets/htl3r-citestyle/harvard-htl3r.csl
  src/lib/pages/bibliography.typ
  src/lib/util.typ
  src/lib/validate.yml
  template/main.typ
  tests/doc/test.typ
  typst.toml
Labels: enhancement

#53 Update documentation to include the newly added citation features
  .gitignore
  README.md
  docs/assets/zit_dir.png
  docs/assets/zit_dir_suppl.png
  docs/assets/zit_ebd.png
  docs/assets/zit_ind.png
  docs/assets/zit_ind_suppl.png
  docs/manual.typ
  src/lib.typ
  template/main.typ
  tests/doc/abbr.yml
  tests/doc/chapter/example.typ
  tests/doc/test.typ
Labels: documentation

#55 Prepare for submission to typst/packages
  .gitignore
  README.md
  docs/assets/zit_dir.png
  docs/assets/zit_dir_suppl.png
  docs/assets/zit_ebd.png
  docs/assets/zit_ind.png
  docs/assets/zit_ind_suppl.png
  docs/manual.pdf
  docs/manual.typ
  src/lib.typ
  src/lib/abbr.typ
  src/lib/breadcrumbs.typ
  src/lib/bubble.typ
  src/lib/pages/bibliography.typ
  src/lib/pages/tof.typ
  src/lib/pages/tol.typ
  src/lib/pages/tot.typ
  template/chapter/example.typ
  template/main.typ
  tests/doc/chapter/example.typ
  thumbnail.png
Labels: documentation

#56 replace school website with gh repository url
  typst.toml
Labels: documentation

#59 update manual to be a little bit more "professional"
  docs/manual.pdf
  docs/manual.typ
Labels: documentation

#65 fixed by moving page counter reset
  src/lib.typ
Labels: bug

#66 make bib and abbr independent of disable-cover
  src/lib.typ
Labels: bug
