Repository HTL3R-Typst/htl3r-da, pull requests merged in 2025-03, with the labels that each got.

#97 92 inconsistent spacing for headings at page start
  docs/manual.pdf
  src/lib.typ
  src/lib/pages/tof.typ
Labels: bug

#100 make cites available in captions
  src/lib.typ
Labels: enhancement

#102 made code-blocks refable
  src/lib/util.typ
Labels: enhancement

#104 Remove deprecated features from the manual
  docs/assets/zit_ebd.png
  docs/manual.typ
  tests/doc/chapter/example.typ
Labels: documentation
